"use client";

import { useEffect, useMemo, useState } from "react";
import {
  ArrowLeft, ArrowRight, BarChart3, Bell, BookOpen, Check, ChevronDown,
  CircleHelp, Clock3, Copy, Ellipsis, Eye, FileText, Flame, GraduationCap,
  Home, LayoutGrid, Library, Lock, LogOut, Mail, Menu, MessageSquareText,
  MoreHorizontal, Play, Plus, Search, Settings, Sparkles, Trophy, Users, X, Zap,
} from "lucide-react";

type View = "landing" | "login" | "dashboard" | "sessions" | "library" | "reports" | "classes" | "students" | "settings" | "help" | "create" | "host" | "join" | "report";
type Question = { prompt: string; answers: string[]; correct: number; seconds: number };
type ClassRecord = { id:string; name:string };
type ActivityRecord = { id:string; title:string; classId:string; questions:Question[] };

const starterQuestions: Question[] = [
  { prompt: "Type your first question here...", answers: ["Option A", "Option B", "Option C", "Option D"], correct: 0, seconds: 20 },
];

const nav = [
  ["dashboard", "Home", Home], ["sessions", "Sessions", Zap], ["library", "My library", Library],
  ["reports", "Reports", BarChart3], ["classes", "Classes", GraduationCap], ["students", "Students", Users],
] as const;

function Avatar({ name, tone = "blue" }: { name: string; tone?: string }) {
  return <span className={`avatar ${tone}`}>{name.split(" ").map((x) => x[0]).slice(0, 2).join("")}</span>;
}

function Logo({ compact = false }: { compact?: boolean }) {
  return <button className="logo" aria-label="PulseClass home"><span className="logo-mark"><i /><i /><i /></span>{!compact && <b>pulse<span>class</span></b>}</button>;
}

export default function PulseClass() {
  const [view, setView] = useState<View>("landing");
  const [mobileNav, setMobileNav] = useState(false);
  const [questions, setQuestions] = useState<Question[]>(starterQuestions);
  const [activeQuestion, setActiveQuestion] = useState(0);
  const [sessionStarted, setSessionStarted] = useState(false);
  const [selectedAnswer, setSelectedAnswer] = useState<number | null>(null);
  const [joined, setJoined] = useState(false);
  const [nickname, setNickname] = useState("");
  const [toast, setToast] = useState("");
  const [activitySaved, setActivitySaved] = useState(false);
  const [activityTitle, setActivityTitle] = useState("Untitled activity");
  const [studentConnected, setStudentConnected] = useState(false);
  const [studentResponse, setStudentResponse] = useState<number | null>(null);
  const [studentFromHost, setStudentFromHost] = useState(false);
  const [rollNumber, setRollNumber] = useState("");
  const [requireRoll, setRequireRoll] = useState(true);
  const [className, setClassName] = useState("");
  const [students, setStudents] = useState<Array<{name:string;roll:string}>>([]);
  const [classes, setClasses] = useState<ClassRecord[]>([]);
  const [activities, setActivities] = useState<ActivityRecord[]>([]);
  const [activeClassId, setActiveClassId] = useState("");
  const [editingActivityId, setEditingActivityId] = useState("");

  useEffect(() => { if (!toast) return; const id = setTimeout(() => setToast(""), 2200); return () => clearTimeout(id); }, [toast]);
  useEffect(() => { try { let savedClasses:ClassRecord[]=JSON.parse(window.localStorage.getItem("pulseclass-classes")||"[]");const legacyClass=window.localStorage.getItem("pulseclass-class");if(!savedClasses.length&&legacyClass)savedClasses=[{id:"class-1",name:legacyClass}];setClasses(savedClasses);if(savedClasses[0]){setActiveClassId(savedClasses[0].id);setClassName(savedClasses[0].name);}let savedActivities:ActivityRecord[]=JSON.parse(window.localStorage.getItem("pulseclass-activities")||"[]");const legacyActivity=window.localStorage.getItem("pulseclass-activity");if(!savedActivities.length&&legacyActivity&&savedClasses[0]){const data=JSON.parse(legacyActivity);savedActivities=[{id:"activity-1",title:data.title||"Untitled activity",classId:savedClasses[0].id,questions:data.questions||starterQuestions}];}setActivities(savedActivities);if(savedActivities[0]){setQuestions(savedActivities[0].questions);setActivityTitle(savedActivities[0].title);setEditingActivityId(savedActivities[0].id);setActivitySaved(true);}window.localStorage.setItem("pulseclass-classes",JSON.stringify(savedClasses));window.localStorage.setItem("pulseclass-activities",JSON.stringify(savedActivities));const roster=window.localStorage.getItem("pulseclass-students");if(roster)setStudents(JSON.parse(roster)); } catch {} }, []);
  const go = (next: View) => { setView(next); setMobileNav(false); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const saveActivity = () => { const input=document.querySelector<HTMLInputElement>(".builder-bar input");const title=input?.value.trim()||activityTitle||"Untitled activity";const id=editingActivityId||`activity-${Date.now()}`;const record={id,title,classId:activeClassId,questions};const next=editingActivityId?activities.map(a=>a.id===id?record:a):[...activities,record];setActivities(next);setEditingActivityId(id);setActivityTitle(title);window.localStorage.setItem("pulseclass-activities",JSON.stringify(next));setActivitySaved(true);setToast(`“${title}” saved in ${className}`); };
  const presentActivity = () => { setSessionStarted(false); setStudentResponse(null); setSelectedAnswer(null); setStudentConnected(false); setJoined(false); setActiveQuestion(0); go("host"); };
  const openCreate = (classId?:string) => { const target=classId||activeClassId||classes[0]?.id;if(!target){setToast("Create a class before adding an activity");go("classes");return;}const cls=classes.find(c=>c.id===target);setActiveClassId(target);setClassName(cls?.name||"");setEditingActivityId("");setActivityTitle("Untitled activity");setQuestions(starterQuestions);go("create"); };
  const editActivity=(activity:ActivityRecord)=>{const cls=classes.find(c=>c.id===activity.classId);setActiveClassId(activity.classId);setClassName(cls?.name||"");setEditingActivityId(activity.id);setActivityTitle(activity.title);setQuestions(activity.questions);go("create");};
  const presentSaved=(activity?:ActivityRecord)=>{if(activity){const cls=classes.find(c=>c.id===activity.classId);setActiveClassId(activity.classId);setClassName(cls?.name||"");setActivityTitle(activity.title);setQuestions(activity.questions);}presentActivity();};
  const connectStudent = () => { setStudentConnected(true); const next={name:nickname.trim(),roll:rollNumber.trim()}; setStudents(current=>{const filtered=current.filter(s=>(next.roll?s.roll!==next.roll:s.name.toLowerCase()!==next.name.toLowerCase()));const updated=[...filtered,next];window.localStorage.setItem("pulseclass-students",JSON.stringify(updated));return updated;}); };

  if (view === "landing") return <Landing onTeacher={() => go("login")} onStudent={() => {setStudentFromHost(false);go("join")}} />;
  if (view === "login") return <TeacherLogin onLogin={() => go("dashboard")} onBack={() => go("landing")} onStudent={() => {setStudentFromHost(false);go("join")}} />;

  return <main className={`app view-${view}`}>
    {toast && <div className="toast"><Check size={17} />{toast}</div>}
    {view === "join" ? <StudentView joined={joined} setJoined={setJoined} nickname={nickname} setNickname={setNickname} rollNumber={rollNumber} setRollNumber={setRollNumber} requireRoll={requireRoll} selected={selectedAnswer} setSelected={setSelectedAnswer} questions={questions} current={activeQuestion} sessionStarted={sessionStarted} onConnect={connectStudent} onResponse={setStudentResponse} teacherPreview={studentFromHost} onExit={() => { if(studentFromHost){go("host")}else{setJoined(false);setSelectedAnswer(null);go("landing")} }} /> : <>
      <aside className={mobileNav ? "sidebar open" : "sidebar"}>
        <div className="side-top"><Logo /><button className="close-mobile" onClick={() => setMobileNav(false)}><X /></button></div>
        <nav>
          {nav.map(([id, label, Icon]) => <button key={id} className={view === id || (id === "sessions" && view === "host") || (id === "reports" && view === "report") ? "active" : ""} onClick={() => go(id as View)}><Icon size={19} /><span>{label}</span></button>)}
        </nav>
        <div className="side-section"><small>WORKSPACE · {classes.length}</small><button onClick={() => go("classes")}><span className="class-dot">{className?className.slice(0,2).toUpperCase():'+'}</span><span>{className||'No classes yet'}</span><ChevronDown size={15} /></button></div>
        <div className="side-tip"><span><Sparkles size={16} /> PRO TIP</span><p>Create a class first, then invite students with a simple join code.</p><button onClick={() => go("classes")}>Create a class <ArrowRight size={14} /></button></div>
        <div className="side-bottom"><button className={view === "help" ? "active" : ""} onClick={() => go("help")}><CircleHelp size={19} /> Help & resources</button><button className={view === "settings" ? "active" : ""} onClick={() => go("settings")}><Settings size={19} /> Settings</button><div className="profile"><Avatar name="Srikanth Reddy" /><div><b>Srikanth Reddy</b><span>teacher@pulseclass.test</span></div><button className="profile-logout" onClick={() => go("landing")} aria-label="Sign out"><LogOut size={17}/></button></div></div>
      </aside>
      <section className="workspace">
        <Header onMenu={() => setMobileNav(true)} onJoin={() => {setStudentFromHost(false);go("join")}} notify={setToast} />
        {view === "dashboard" && <Dashboard saved={activities.length>0} title={activities[0]?.title||activityTitle} className={classes.find(c=>c.id===activities[0]?.classId)?.name||className} onCreate={()=>openCreate()} onHost={()=>presentSaved(activities[0])} onReport={() => go("reports")} />}
        {view === "sessions" && <SessionsPage hasActivity={activitySaved} title={activityTitle} className={className} live={sessionStarted||studentConnected} onLibrary={()=>go("library")} onPresent={presentActivity}/>} 
        {view === "library" && (activities.length ? <MultiLibraryPage classes={classes} activities={activities} onCreate={openCreate} onEdit={editActivity} onPresent={presentSaved}/> : <WorkspaceEmpty type="library" onAction={()=>openCreate()} />)}
        {view === "reports" && <WorkspaceEmpty type="reports" onAction={() => go("sessions")} />}
        {view === "classes" && <MultiClassPage classes={classes} activities={activities} onSave={(name)=>{const record={id:`class-${Date.now()}`,name};const next=[...classes,record];setClasses(next);setActiveClassId(record.id);setClassName(name);window.localStorage.setItem("pulseclass-classes",JSON.stringify(next));setToast("Class created");}} onAddActivity={openCreate}/>} 
        {view === "students" && <StudentsPage students={students}/>} 
        {view === "settings" && <SettingsPage requireRoll={requireRoll} setRequireRoll={setRequireRoll} notify={setToast} />}
        {view === "help" && <HelpPage notify={setToast} />}
        {view === "create" && <CreateQuiz title={activityTitle} questions={questions} setQuestions={setQuestions} onBack={() => go("dashboard")} onSave={saveActivity} onLaunch={() => {saveActivity();presentActivity()}} notify={(message)=>message==="Quiz saved"?saveActivity():setToast(message)} />}
        {view === "host" && <HostView questions={questions} current={activeQuestion} setCurrent={setActiveQuestion} started={sessionStarted} setStarted={setSessionStarted} connected={studentConnected} response={studentResponse} onExit={() => go("dashboard")} onJoin={() => {setStudentFromHost(true);go("join")}} onReport={() => go("report")} notify={setToast} />}
        {view === "report" && <WorkspaceEmpty type="reports" onAction={() => go("sessions")} />}
      </section>
    </>}
  </main>;
}

function Landing({ onTeacher, onStudent }: { onTeacher: () => void; onStudent: () => void }) {
  const [code,setCode]=useState("");
  return <main className="student-index"><header><Logo/></header><section><div className="student-index-copy"><span><i/> LIVE CLASSROOM</span><h1>Your class is<br/>ready when <em>you are.</em></h1><p>Enter the six-digit code shown by your teacher to join the activity. No account or password needed.</p></div><div className="quick-join"><span><Zap/></span><h2>Join your class</h2><p>Enter the session code from your teacher.</p><label>SESSION CODE<input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="000 000" inputMode="numeric"/></label><button className="primary" disabled={code.length!==6} onClick={onStudent}>Continue <ArrowRight/></button><small><Lock/> Your response is private and secure.</small></div></section><footer><span>© 2026 PulseClass</span><button onClick={onTeacher}><Lock/> Teacher portal</button></footer></main>;
}

function TeacherLogin({ onLogin, onBack, onStudent }: { onLogin: () => void; onBack: () => void; onStudent: () => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [show, setShow] = useState(false); const [error, setError] = useState("");
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (email.trim().toLowerCase() !== "teacher@pulseclass.test" || password !== "Pulse@2026") { setError("The username or password is incorrect."); return; } setError(""); onLogin(); };
  return <main className="login-page"><button className="login-brand" onClick={onBack}><Logo/></button><section className="login-story"><div><span className="landing-kicker"><i/> TEACH WITH THE WHOLE ROOM</span><h1>Your classroom is<br/>waiting to <em>light up.</em></h1><p>Run live activities, involve every student, and see understanding take shape in real time.</p><div className="login-quote"><div className="quote-avatars"><Avatar name="AR" tone="coral"/><Avatar name="LK" tone="blue"/><Avatar name="SM" tone="mint"/></div><blockquote>“I finally hear from students who never used to raise their hands.”</blockquote><small>— Maya Chen, Computer Science</small></div></div><div className="story-orbit o1"/><div className="story-orbit o2"/></section><section className="login-form-wrap"><form className="login-form" onSubmit={submit}><span className="form-badge"><GraduationCap/></span><h2>Teacher sign in</h2><p>Use the test teacher account to enter the workspace.</p><div className="test-account"><Sparkles/><div><b>TEST ACCOUNT</b><span>teacher@pulseclass.test</span><span>Pulse@2026</span></div></div><label>Username<div><Mail/><input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} placeholder="teacher@pulseclass.test"/></div></label><label>Password<div><Lock/><input type={show?"text":"password"} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password"/><button type="button" onClick={()=>setShow(!show)} aria-label="Show password"><Eye/></button></div></label>{error&&<p className="form-error">{error}</p>}<button className="primary login-submit" type="submit">Sign in to PulseClass <ArrowRight/></button><div className="student-divider"/><button type="button" className="student-login-link" onClick={onStudent}><Users/> Joining a class? <b>Enter your session code</b><ArrowRight/></button></form></section></main>;
}

function Header({ onMenu, onJoin, notify }: { onMenu: () => void; onJoin: () => void; notify: (s:string)=>void }) {
  return <header className="topbar"><button className="menu" onClick={onMenu}><Menu /></button><div className="mobile-logo"><Logo /></div><div className="top-search"><Search size={18} /><input placeholder="Search your workspace..." onKeyDown={e=>{if(e.key==='Enter')notify('No results in your new workspace')}}/><kbd>⌘ K</kbd></div><button className="join-link" onClick={onJoin}>Join as student</button><button className="icon-btn" onClick={()=>notify('You’re all caught up')} aria-label="Notifications"><Bell size={20} /></button><Avatar name="Srikanth Reddy" /></header>;
}

const emptyContent = {
  sessions: { eyebrow:"LIVE & ASSIGNED", title:"Sessions", description:"Run activities live or assign them for students to complete at their own pace.", icon:Zap, empty:"No sessions yet", detail:"Choose an activity from your library to start your first session.", action:"Choose an activity" },
  library: { eyebrow:"YOUR CONTENT", title:"My library", description:"Create and organize quizzes, polls, word clouds, and exit tickets.", icon:Library, empty:"Your library is empty", detail:"Create your first activity from scratch. It only takes a few minutes.", action:"Create activity" },
  reports: { eyebrow:"LEARNING INSIGHTS", title:"Reports", description:"Review participation, accuracy, and question-level understanding after every session.", icon:BarChart3, empty:"No reports yet", detail:"Reports are created automatically when you complete a session.", action:"View sessions" },
  classes: { eyebrow:"PEOPLE & GROUPS", title:"Classes", description:"Organize students into classes and make recurring sessions easier to manage.", icon:Users, empty:"Create your first class", detail:"Add a class name and invite students using a secure join code.", action:"Create class" },
} as const;

function WorkspaceEmpty({type,onAction}:{type:keyof typeof emptyContent;onAction:()=>void}) { const item=emptyContent[type]; const Icon=item.icon; return <div className="page module-page"><div className="module-head"><div><p>{item.eyebrow}</p><h1>{item.title}</h1><span>{item.description}</span></div><button className="primary" onClick={onAction}><Plus/>{item.action}</button></div><div className="module-tools"><div><Search/><input placeholder={`Search ${item.title.toLowerCase()}...`}/></div><button>All <ChevronDown/></button><button>Recently updated <ChevronDown/></button></div><section className="module-empty"><span><Icon/></span><h2>{item.empty}</h2><p>{item.detail}</p><button className="primary" onClick={onAction}><Plus/>{item.action}</button></section></div>; }

function SavedActivityPage({mode,title,className,onCreate,onPresent}:{mode:"library"|"sessions";title:string;className:string;onCreate:()=>void;onPresent:()=>void}) { return <div className="page module-page"><div className="module-head"><div><p>{mode==='library'?'YOUR CONTENT':'LIVE & ASSIGNED'}</p><h1>{mode==='library'?'My library':'Sessions'}</h1><span>{mode==='library'?'Your saved activities are grouped by their parent class.':'Choose a saved activity and start a live classroom session.'}</span></div><button className="primary" onClick={onCreate}><Plus/>Create activity</button></div><div className="library-class-group"><header><span className="class-dot">{className.slice(0,2).toUpperCase()}</span><div><b>{className}</b><small>1 activity</small></div></header><section className="saved-activity-list"><div className="saved-activity-thumb"><span>QUIZ</span><div><i/><i/><i/><i/></div></div><div className="saved-activity-info"><span>{className.toUpperCase()} · DRAFT</span><h2>{title}</h2><p>Saved just now · Linked to {className}</p></div><button className="secondary" onClick={onCreate}>Edit</button><button className="primary" onClick={onPresent}><Play/>Present</button></section></div></div>; }

function MultiLibraryPage({classes,activities,onCreate,onEdit,onPresent}:{classes:ClassRecord[];activities:ActivityRecord[];onCreate:(classId?:string)=>void;onEdit:(a:ActivityRecord)=>void;onPresent:(a?:ActivityRecord)=>void}) { return <div className="page module-page"><div className="module-head"><div><p>YOUR CONTENT</p><h1>My library</h1><span>{activities.length} {activities.length===1?'activity':'activities'} organized across {classes.length} {classes.length===1?'class':'classes'}.</span></div><button className="primary" onClick={()=>onCreate()}><Plus/>Create activity</button></div>{classes.map(cls=>{const items=activities.filter(a=>a.classId===cls.id);return <section className="library-class-group multi" key={cls.id}><header><span className="class-dot">{cls.name.slice(0,2).toUpperCase()}</span><div><b>{cls.name}</b><small>{items.length} {items.length===1?'activity':'activities'}</small></div><button onClick={()=>onCreate(cls.id)}><Plus/>Add activity</button></header>{items.length?items.map(activity=><div className="saved-activity-list" key={activity.id}><div className="saved-activity-thumb"><span>QUIZ</span><div><i/><i/><i/><i/></div></div><div className="saved-activity-info"><span>{cls.name.toUpperCase()} · DRAFT</span><h2>{activity.title}</h2><p>{activity.questions.length} questions · Linked to {cls.name}</p></div><button className="secondary" onClick={()=>onEdit(activity)}>Edit</button><button className="primary" onClick={()=>onPresent(activity)}><Play/>Present</button></div>):<div className="class-no-activity">No activities in this class yet.</div>}</section>})}</div>; }

function MultiClassPage({classes,activities,onSave,onAddActivity}:{classes:ClassRecord[];activities:ActivityRecord[];onSave:(name:string)=>void;onAddActivity:(classId?:string)=>void}) { const [name,setName]=useState("");const [adding,setAdding]=useState(classes.length===0);return <div className="page module-page"><div className="module-head"><div><p>CLASS WORKSPACES</p><h1>Classes</h1><span>Create separate spaces for each course, section, or learning group.</span></div><button className="primary" onClick={()=>setAdding(true)}><Plus/>Create class</button></div>{adding&&<section className="panel inline-class-form"><label>New class name<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. B.Tech CSE — Section B"/></label><button className="secondary" onClick={()=>{setAdding(false);setName('')}}>Cancel</button><button className="primary" disabled={!name.trim()} onClick={()=>{onSave(name.trim());setName('');setAdding(false)}}>Save class</button></section>}<div className="classes-grid">{classes.map(cls=>{const count=activities.filter(a=>a.classId===cls.id).length;return <article className="panel class-card" key={cls.id}><span className="class-dot">{cls.name.slice(0,2).toUpperCase()}</span><div><h2>{cls.name}</h2><p>{count} {count===1?'activity':'activities'} · 0 completed sessions</p></div><button className="primary" onClick={()=>onAddActivity(cls.id)}><Plus/>Add activity</button></article>})}</div></div>; }

function SessionsPage({hasActivity,title,className,live,onLibrary,onPresent}:{hasActivity:boolean;title:string;className:string;live:boolean;onLibrary:()=>void;onPresent:()=>void}) { return <div className="page module-page"><div className="module-head"><div><p>DELIVERY & ATTEMPTS</p><h1>Sessions</h1><span>Start live runs and review their operational status. Activities themselves live in My library.</span></div>{hasActivity&&<button className="primary" onClick={onPresent}><Play/>Start live session</button>}</div><div className="session-tabs"><button className="active">Live & scheduled</button><button>Completed</button></div>{live?<section className="session-run-card"><span className="live-pill"><i/> LIVE</span><div><h2>{title}</h2><p>{className} · Join code 482 938</p></div><strong>1 connected</strong><button className="primary" onClick={onPresent}>Open host view</button></section>:<section className="module-empty standalone"><span><Zap/></span><h2>No sessions running</h2><p>{hasActivity?`${title} in ${className} is ready to present.`:'Create an activity in My library before starting a session.'}</p><button className="primary" onClick={hasActivity?onPresent:onLibrary}>{hasActivity?<Play/>:<Library/>}{hasActivity?'Start session':'Open My library'}</button></section>}</div>; }

function ClassPage({className,onSave,onAddActivity}:{className:string;onSave:(name:string)=>void;onAddActivity:()=>void}) { const [name,setName]=useState(className); if(className)return <div className="page module-page"><div className="module-head"><div><p>CLASS WORKSPACE</p><h1>{className}</h1><span>Activities, students, and sessions are organized inside this class.</span></div><button className="primary" onClick={onAddActivity}><Plus/>Add activity</button></div><section className="class-summary"><div><GraduationCap/></div><span><b>{className}</b><small>0 saved activities · 0 completed sessions</small></span><em>ACTIVE</em></section></div>; return <div className="page module-page"><div className="module-head"><div><p>CLASS SETUP</p><h1>Create your first class</h1><span>An activity must belong to a class. Configure the class before creating content.</span></div></div><section className="panel class-form"><span><GraduationCap/></span><h2>Class details</h2><p>Give this learning group a clear name. You can invite students after saving.</p><label>Class name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. B.Tech CSE — Section A"/></label><button className="primary" disabled={!name.trim()} onClick={()=>onSave(name.trim())}>Create class <ArrowRight/></button></section></div>; }

function StudentsPage({students}:{students:Array<{name:string;roll:string}>}) { return <div className="page module-page"><div className="module-head"><div><p>UNIQUE PARTICIPANTS</p><h1>Students</h1><span>Each roll number is counted once, even if the student reconnects.</span></div><div className="student-total"><Users/><span><b>{students.length}</b><small>unique students</small></span></div></div>{students.length?<section className="panel roster"><header><span>Student</span><span>Roll number</span><span>Status</span></header>{students.map(student=><div key={student.roll||student.name}><span><Avatar name={student.name}/><b>{student.name}</b></span><code>{student.roll||'Not required'}</code><em><i/> Connected</em></div>)}</section>:<section className="module-empty standalone"><span><Users/></span><h2>No students have connected</h2><p>Students appear here after joining a session with the required identity fields.</p></section>}</div>; }

function SettingsPage({requireRoll,setRequireRoll,notify}:{requireRoll:boolean;setRequireRoll:(v:boolean)=>void;notify:(s:string)=>void}) { const [sounds,setSounds]=useState(true); return <div className="page module-page"><div className="module-head"><div><p>ACCOUNT & PARTICIPATION</p><h1>Settings</h1><span>Control how students identify themselves when joining.</span></div><button className="primary" onClick={()=>notify('Settings saved')}>Save changes</button></div><div className="settings-layout"><nav><button>Profile</button><button className="active">Student identity</button><button>Notifications</button><button>Accessibility</button></nav><section className="panel settings-panel"><h2>Student join requirements</h2><p>Choose the information every student must provide before entering a session.</p><label className="professional-toggle"><span><b>Student name</b><small>Always required so the teacher can recognize participants.</small></span><input type="checkbox" checked disabled/></label><label className="professional-toggle"><span><b>Roll number</b><small>Require a unique institutional roll number and use it for deduplication.</small></span><input type="checkbox" checked={requireRoll} onChange={e=>setRequireRoll(e.target.checked)}/></label><hr/><h3>Session preferences</h3><label className="professional-toggle"><span><b>Classroom sounds</b><small>Play subtle sounds for joins and responses.</small></span><input type="checkbox" checked={sounds} onChange={e=>setSounds(e.target.checked)}/></label></section></div></div>; }

function HelpPage({notify}:{notify:(s:string)=>void}) { return <div className="page module-page"><div className="help-hero"><span><CircleHelp/></span><p>HELP CENTER</p><h1>How can we help, Srikanth?</h1><div><Search/><input placeholder="Search guides and answers..." onKeyDown={e=>{if(e.key==='Enter')notify('Search ready — type a help topic')}}/></div></div><div className="help-grid"><button onClick={()=>notify('Getting started guide opened')}><Zap/><span><b>Getting started</b><small>Create and run your first activity.</small></span><ArrowRight/></button><button onClick={()=>notify('Live sessions guide opened')}><Play/><span><b>Running live sessions</b><small>Host, present, and manage responses.</small></span><ArrowRight/></button><button onClick={()=>notify('Student guide opened')}><Users/><span><b>Student participation</b><small>Joining, accessibility, and privacy.</small></span><ArrowRight/></button><button onClick={()=>notify('Reports guide opened')}><BarChart3/><span><b>Reports & insights</b><small>Understand results and export data.</small></span><ArrowRight/></button></div><section className="panel support-card"><div><MessageSquareText/><span><b>Still need help?</b><small>Our classroom support team typically replies within one business day.</small></span></div><button className="secondary" onClick={()=>notify('Support request started')}>Contact support</button></section></div>; }

function Dashboard({ saved, title, className, onCreate, onHost, onReport }: { saved:boolean; title:string; className:string; onCreate: () => void; onHost: () => void; onReport: () => void }) {
  return <div className="page dashboard-page">
    <div className="welcome"><div><p>MONDAY, AUGUST 3</p><h1>Welcome to PulseClass, Srikanth <span>👋</span></h1><h2>{saved?'Your classroom content is ready to use.':'Your new teacher workspace is ready.'}</h2></div><button className="primary" onClick={onCreate}><Plus size={19} /> {saved?'Create activity':'Create first activity'}</button></div>
    {saved?<section className="active-home-hero"><div><span><i/> READY TO PRESENT</span><h2>{title}</h2><p>{className} · Saved activity</p><button className="light-button" onClick={onHost}><Play/>Start live session</button></div><div className="active-home-metric"><b>1</b><span>activity ready</span></div></section>:<section className="empty-welcome"><div className="empty-spark"><Sparkles/></div><span>YOUR FIRST CLASS STARTS HERE</span><h2>Let’s create something<br/>your students will love.</h2><p>Build a quick quiz, poll, or exit ticket. When you’re ready, share a code and bring everyone into the conversation.</p><button className="primary" onClick={onCreate}><Plus/> Create your first activity</button><div className="first-steps"><div><b>1</b><span><strong>Create</strong><small>Build an activity</small></span></div><i/><div><b>2</b><span><strong>Share</strong><small>Give students a code</small></span></div><i/><div><b>3</b><span><strong>Learn</strong><small>See live understanding</small></span></div></div></section>}
    <div className="section-title"><div><h3>At a glance</h3><p>Your classroom activity this week</p></div><button>This week <ChevronDown size={15}/></button></div>
    <div className="stats-grid">
      <Stat icon={<Zap/>} tone="coral" value="0" label="Sessions run" trend="New" />
      <Stat icon={<Users/>} tone="blue" value="0" label="Students reached" trend="New" />
      <Stat icon={<MessageSquareText/>} tone="mint" value="0" label="Responses" trend="New" />
      <Stat icon={<Flame/>} tone="gold" value="—" label="Avg. engagement" trend="New" />
    </div>
    <div className="fresh-grid"><section className="panel fresh-panel"><div className="panel-head"><div><h3>Recent sessions</h3><p>Your completed sessions will appear here</p></div></div><div className="small-empty"><span><Clock3/></span><b>No completed sessions</b><p>Present your saved activity to begin.</p></div></section><section className="panel fresh-panel"><div className="panel-head"><div><h3>My library</h3><p>{className||'Your saved activities'}</p></div></div>{saved?<button className="dashboard-saved" onClick={onHost}><span>QUIZ</span><div><b>{title}</b><small>{className} · Saved just now</small></div><Play/></button>:<button className="small-empty clickable" onClick={onCreate}><span><Plus/></span><b>Create an activity</b><p>Quiz, poll, word cloud & more</p></button>}</section></div>
  </div>;
}

function Stat({ icon, tone, value, label, trend }: { icon: React.ReactNode; tone: string; value: string; label: string; trend: string }) { return <div className="stat"><span className={`stat-icon ${tone}`}>{icon}</span><div><strong>{value}</strong><p>{label}</p></div><em>{trend}</em></div>; }
function SessionRow({ icon, tone, title, meta, score, onClick }: { icon:string; tone:string; title:string; meta:string; score:string; onClick:()=>void }) { return <button className="session-row" onClick={onClick}><span className={`session-icon ${tone}`}>{icon}</span><span><b>{title}</b><small>{meta}</small></span><span className="engage"><b>{score}</b><small>engagement</small></span><MoreHorizontal size={19}/></button>; }
function QuizCard({ tone, label, title, details, plays, onClick }: {tone:string;label:string;title:string;details:string;plays:string;onClick:()=>void}) { return <button className="quiz-card" onClick={onClick}><div className={`quiz-art ${tone}`}><span>{label}</span><div className="mini-bars"><i/><i/><i/><i/></div></div><div className="quiz-info"><h4>{title}</h4><p>{details}</p><footer><span>{plays}</span><MoreHorizontal size={18}/></footer></div></button>; }

function CreateQuiz({ title, questions, setQuestions, onBack, onSave, onLaunch, notify }: { title:string;questions:Question[];setQuestions:(q:Question[])=>void;onBack:()=>void;onSave:()=>void;onLaunch:()=>void;notify:(s:string)=>void }) {
  const [selected, setSelected] = useState(0); const q = questions[selected];
  useEffect(()=>{const input=document.querySelector<HTMLInputElement>(".builder-bar input");if(input)input.value=title;},[title]);
  const update = (patch: Partial<Question>) => setQuestions(questions.map((item, i) => i === selected ? {...item, ...patch} : item));
  const add = () => { setQuestions([...questions, {prompt:"Type your question here...",answers:["Option A","Option B","Option C","Option D"],correct:0,seconds:20}]); setSelected(questions.length); };
  return <div className="builder"><div className="builder-bar"><button onClick={onBack}><ArrowLeft/> <span>Exit</span></button><input defaultValue="JavaScript Fundamentals"/><div><button className="secondary" onClick={()=>notify("Quiz saved")}>Save</button><button className="primary" onClick={onLaunch}><Play size={17}/> Present</button></div></div><div className="builder-body"><aside className="slides"><div><b>Questions</b><span>{questions.length}</span></div>{questions.map((item,i)=><button key={i} className={i===selected?"selected":""} onClick={()=>setSelected(i)}><em>{i+1}</em><span><small>{item.seconds}s</small><b>{item.prompt}</b><i/><i/></span></button>)}<button className="add-question" onClick={add}><Plus/> Add question</button></aside><section className="canvas"><div className="question-type"><span><LayoutGrid size={17}/> Multiple choice</span><span><Clock3 size={17}/> {q.seconds} sec</span><span><Trophy size={17}/> Standard points</span></div><textarea value={q.prompt} onChange={e=>update({prompt:e.target.value})}/><div className="answer-editor">{q.answers.map((answer,i)=><div className={`edit-answer a${i}`} key={i}><button onClick={()=>update({correct:i})} className={q.correct===i?"correct":""}>{q.correct===i?<Check/>:String.fromCharCode(65+i)}</button><input value={answer} onChange={e=>update({answers:q.answers.map((a,j)=>j===i?e.target.value:a)})}/></div>)}</div><p className="canvas-hint"><Check size={15}/> Click an answer letter to mark it correct</p></section><aside className="properties"><h3>Question settings</h3><label>Time limit<select value={q.seconds} onChange={e=>update({seconds:Number(e.target.value)})}><option value="10">10 seconds</option><option value="15">15 seconds</option><option value="20">20 seconds</option><option value="30">30 seconds</option></select></label><label>Points<select><option>Standard — 1,000</option><option>Double — 2,000</option><option>No points</option></select></label><label className="toggle-line">Randomize answers <input type="checkbox" defaultChecked/></label><hr/><h3>Enhance</h3><button className="enhance"><Sparkles/> Generate with AI</button><button className="enhance"><BookOpen/> Add explanation</button></aside></div></div>;
}

function HostView({questions,current,setCurrent,started,setStarted,connected,response,onExit,onJoin,onReport,notify}:{questions:Question[];current:number;setCurrent:(n:number)=>void;started:boolean;setStarted:(b:boolean)=>void;connected:boolean;response:number|null;onExit:()=>void;onJoin:()=>void;onReport:()=>void;notify:(s:string)=>void}) {
  const q=questions[current]; const last=current===questions.length-1;
  if(!started) return <div className="lobby"><div className="host-top"><Logo/><button onClick={onExit}><X/> End session</button></div><div className="lobby-content"><span className="live-pill"><i/> LOBBY OPEN</span><h1>Join the session</h1><p>Use the student preview or enter this code</p><div className="join-code"><strong>482 938</strong><button onClick={()=>{navigator.clipboard?.writeText("482938");notify("Join code copied")}}><Copy/></button></div><div className="lobby-actions"><button className="secondary" onClick={onJoin}><Users/> Open student test</button><button className="primary" onClick={()=>setStarted(true)}><Play fill="currentColor"/> Start session</button></div><div className="participants">{connected?<><div><Avatar name="Test Student" tone="mint"/></div><b>1 student connected</b><span>Test Student is ready to begin.</span></>:<><div className="waiting-avatar"><Users/></div><b>No students connected</b><span>Open the student test, enter a name, then return here.</span></>}</div></div></div>;
  const counts=q.answers.map((_,i)=>response===i?1:0);
  return <div className="host-screen"><header><button onClick={onExit}><X/></button><span>UNTITLED ACTIVITY</span><div><Users size={17}/> {connected?1:0} <span>·</span> <b>{current+1} / {questions.length}</b></div></header><section><div className="host-question-head"><span>QUESTION {current+1}</span><div className="timer">{q.seconds}</div><span>1,000 PTS</span></div><h1>{q.prompt}</h1><div className="host-answers">{q.answers.map((a,i)=><div className={`host-answer c${i} ${response===i?'live-picked':''}`} key={a}><b>{String.fromCharCode(65+i)}</b><span>{a}</span><em>{counts[i]} response{counts[i]===1?'':'s'}</em></div>)}</div><div className="response-count">{response!==null?<><div><i/></div><b>1 / {connected?1:0} answered live</b></>:<><div/><b>Waiting for a live response…</b></>}</div></section><footer><button onClick={onJoin}><Users/> Student test</button><div><i/> {response!==null?'Response received live':'Listening for student answers'}</div><button className="primary" onClick={()=>{if(last){setStarted(false);onReport()}else setCurrent(current+1)}}>{last?"Finish":"Next"} <ArrowRight/></button></footer></div>;
}

function StudentView({joined,setJoined,nickname,setNickname,rollNumber,setRollNumber,requireRoll,selected,setSelected,questions,current,sessionStarted,onConnect,onResponse,teacherPreview,onExit}:{joined:boolean;setJoined:(b:boolean)=>void;nickname:string;setNickname:(s:string)=>void;rollNumber:string;setRollNumber:(s:string)=>void;requireRoll:boolean;selected:number|null;setSelected:(n:number|null)=>void;questions:Question[];current:number;sessionStarted:boolean;onConnect:()=>void;onResponse:(n:number)=>void;teacherPreview:boolean;onExit:()=>void}) {
  if(!joined) return <div className="student-join"><div className="student-brand"><Logo/></div><button className="exit-join" onClick={onExit}><X/></button><div className="join-panel"><span className="spark">✦</span><h1>Join the room.</h1><p>Enter the details requested by your teacher.</p><label>SESSION CODE<input defaultValue="482 938" inputMode="numeric"/></label><label>FULL NAME<input value={nickname} placeholder="Your full name" onChange={e=>setNickname(e.target.value)}/></label>{requireRoll&&<label>ROLL NUMBER<input value={rollNumber} placeholder="Your unique roll number" onChange={e=>setRollNumber(e.target.value)}/></label>}<button className="primary" onClick={()=>{setJoined(true);onConnect()}} disabled={!nickname.trim()||(requireRoll&&!rollNumber.trim())}>Join session <ArrowRight/></button><small>Your teacher controls which identity fields are required.</small></div><div className="join-decor d1"/><div className="join-decor d2"/><div className="join-decor d3"/></div>;
  if(!sessionStarted) return <div className="student-wait"><header><Logo/><button onClick={onExit}><ArrowLeft/> Teacher view</button></header><main><span><Check/></span><h1>You’re connected, {nickname}!</h1><p>Srikanth can now see you in the lobby. Return to the teacher view and start the session.</p>{teacherPreview&&<button className="primary" onClick={onExit}>Return to teacher lobby <ArrowRight/></button>}</main></div>;
  const q=questions[current];
  return <div className="student-play"><header><Logo/><span><i/> LIVE</span><b>{nickname||"Student"} · {selected===q.correct?'1,000':'0'} pts</b></header><main><button className="teacher-return" onClick={onExit}><ArrowLeft/> Teacher view</button><p>QUESTION {current+1} OF {questions.length}</p><div className="student-timer"><span style={{width:"68%"}}/></div><h1>{q.prompt}</h1><div className="student-answers">{q.answers.map((a,i)=><button className={`s${i} ${selected===i?"picked":""}`} disabled={selected!==null} onClick={()=>{setSelected(i);onResponse(i)}} key={a}><b>{String.fromCharCode(65+i)}</b>{a}{selected===i&&<Check/>}</button>)}</div>{selected!==null?<div className="submitted"><Check/><div><b>Answer submitted live!</b><span>Return to the teacher view to see the response update.</span></div></div>:<p className="tap-hint">Tap an answer to submit</p>}</main></div>;
}

function ReportView({onBack}:{onBack:()=>void}) { const students=[['1','Alex Rivera','AR','9,420','92%','8.2s'],['2','Leah Kim','LK','8,980','89%','9.1s'],['3','Sam Malik','SM','8,640','86%','10.4s'],['4','Nora James','NJ','8,120','84%','11.8s'],['5','Owen Patel','OP','7,890','81%','12.1s']]; return <div className="page report-page"><div className="report-head"><button onClick={onBack}><ArrowLeft/></button><div><p>SESSION REPORT</p><h1>JavaScript Fundamentals</h1><span>August 3, 2026 · 10:30 AM · 24 participants</span></div><button className="secondary"><FileText/> Export report</button></div><div className="report-summary"><div><span className="stat-icon mint"><Users/></span><strong>24</strong><p>Participants</p></div><div><span className="stat-icon coral"><Check/></span><strong>84%</strong><p>Average accuracy</p></div><div><span className="stat-icon blue"><MessageSquareText/></span><strong>96%</strong><p>Completion rate</p></div><div><span className="stat-icon gold"><Clock3/></span><strong>9.8s</strong><p>Average response</p></div></div><div className="report-grid"><section className="panel"><div className="panel-head"><div><h3>Question performance</h3><p>Accuracy across the session</p></div></div>{[92,88,67,84,73,96,79,91].map((n,i)=><div className="question-result" key={i}><b>Q{i+1}</b><div><span style={{width:`${n}%`}}/></div><strong className={n<75?'low':''}>{n}%</strong></div>)}<div className="attention"><Sparkles/><div><b>Worth revisiting</b><p>Students found question 3 on HTTP status codes most challenging.</p></div></div></section><section className="panel leaderboard"><div className="panel-head"><div><h3>Leaderboard</h3><p>Final results</p></div><button>View all</button></div>{students.map(([rank,name,initials,pts,accuracy,time],i)=><div className="leader-row" key={name}><b className={i<3?`rank r${i}`:"rank"}>{rank}</b><Avatar name={initials} tone={i===0?"coral":i===1?"blue":"mint"}/><span><b>{name}</b><small>{accuracy} correct · {time} avg.</small></span><strong>{pts}</strong></div>)}</section></div></div>; }
